name: single_sample CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nextflow
      run: |
        export NXF_VER='19.09.0-edge'
        wget -qO- get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
    - name: Get sample data
      run: |
        wget https://raw.githubusercontent.com/aertslab/scenic-nf/master/example/sample_data.tar.gz
        tar xvf sample_data.tar.gz
        pwd
    - name: Run single_sample test
      run: |
        nextflow run ${GITHUB_WORKSPACE} -profile single_sample,test__single_sample,docker -entry single_sample
    - name: Run single_sample_scenic test
      run: |
        nextflow run ${GITHUB_WORKSPACE} -profile single_sample_scenic,test__single_sample_scenic,docker -entry single_sample_scenic

